# Generated by Django 5.1.1 on 2024-10-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_department_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='base.department'),
        ),
    ]
